import Foundation

/// Static country directory — mirrors `countries_data.dart`. The full
/// E.164 set with popular markets surfaced to the top of the picker.
enum CountriesData {
    /// ISO2 → backend `country_id`. Lifted verbatim from
    /// `lib/core/config/constants/countries_data.dart`.
    private static let dbIds: [String: Int] = [
        "AF": 8, "AL": 9, "DZ": 11, "AS": 12, "AD": 13, "AO": 14, "AQ": 20,
        "AG": 22, "AR": 25, "AW": 28, "AU": 29, "AT": 31, "AZ": 2, "BS": 32,
        "BH": 35, "BD": 37, "BB": 39, "BY": 40, "BE": 41, "BO": 52, "BA": 55,
        "BR": 57, "BN": 60, "BG": 62, "BF": 64, "KH": 69, "CM": 140, "US": 26,
        "CV": 142, "KY": 179, "CF": 75, "TD": 220, "CL": 77, "CN": 79, "CO": 81,
        "KM": 175, "CG": 137, "CK": 139, "CR": 141, "CI": 138, "HR": 83, "CU": 84,
        "CY": 85, "CZ": 86, "DK": 1, "DJ": 143, "DM": 144, "DO": 145, "EC": 146,
        "EG": 89, "SV": 218, "GQ": 161, "EE": 92, "ET": 147, "GS": 80, "FO": 151,
        "FJ": 148, "FI": 97, "FR": 99, "GF": 153, "GM": 158, "GE": 101, "DE": 103,
        "GH": 155, "GI": 156, "GR": 104, "GL": 157, "GD": 152, "GP": 160, "GU": 163,
        "GT": 162, "GB": 33, "GN": 159, "GW": 164, "GY": 165, "HT": 167, "HN": 166,
        "HK": 106, "HU": 107, "IS": 109, "IN": 111, "ID": 112, "IR": 114, "IQ": 168,
        "IE": 115, "IL": 117, "IT": 118, "JM": 170, "JP": 120, "JO": 171, "KZ": 121,
        "KE": 172, "KI": 174, "KW": 178, "KG": 173, "LA": 180, "LV": 124, "LB": 181,
        "LS": 184, "LR": 183, "LI": 182, "LT": 125, "LU": 185, "MO": 194, "MK": 190,
        "MG": 188, "MW": 200, "MY": 128, "MV": 129, "ML": 191, "MT": 198, "MH": 189,
        "MQ": 195, "MR": 196, "MU": 199, "MX": 131, "FM": 150, "MD": 133, "MC": 187,
        "MN": 193, "ME": 132, "MS": 197, "MA": 186, "MZ": 201, "MM": 192, "NA": 202,
        "NR": 208, "NP": 207, "NL": 134, "NC": 203, "PN": 113, "NI": 206, "NE": 204,
        "NG": 205, "NU": 209, "KP": 176, "NO": 130, "PK": 126, "PS": 211, "PA": 123,
        "PG": 210, "PY": 122, "PE": 119, "PH": 116, "PL": 110, "PT": 108, "PR": 105,
        "QA": 102, "RE": 212, "RO": 100, "RU": 98, "RW": 96, "SH": 215, "KN": 221,
        "WS": 95, "SM": 94, "SA": 93, "SN": 91, "RS": 90, "SC": 214, "SL": 216,
        "SG": 88, "SK": 87, "SI": 82, "SB": 213, "SO": 217, "ZA": 223, "KR": 177,
        "SS": 78, "ES": 76, "LK": 74, "SD": 73, "SR": 71, "SZ": 219, "SE": 70,
        "CH": 68, "SY": 67, "TW": 65, "TJ": 63, "TZ": 61, "TH": 59, "TL": 58,
        "TG": 54, "TK": 53, "TO": 51, "TT": 49, "TN": 47, "TR": 45, "TM": 4,
        "TC": 44, "UG": 38, "UA": 36, "AE": 34, "UY": 24, "UZ": 3, "VU": 23,
        "VE": 21, "VN": 19, "VG": 18, "VI": 17, "WF": 15, "YE": 10, "ZM": 7,
        "ZW": 6, "AX": 5,
    ]

    static let all: [Country] = rawEntries.map { entry in
        Country(
            id: entry.id,
            name: entry.name,
            dialCode: entry.dialCode,
            flag: entry.flag,
            isPopular: entry.isPopular,
            dbId: dbIds[entry.id]
        )
    }

    private struct Raw {
        let id: String
        let name: String
        let dialCode: String
        let flag: String
        let isPopular: Bool

        init(id: String, name: String, dialCode: String, flag: String, isPopular: Bool = false) {
            self.id = id
            self.name = name
            self.dialCode = dialCode
            self.flag = flag
            self.isPopular = isPopular
        }
    }

    private static let rawEntries: [Raw] = [
        // Popular markets — float to the top of the picker.
        Raw(id: "AZ", name: "Azerbaijan",    dialCode: "+994", flag: "🇦🇿", isPopular: true),
        Raw(id: "TR", name: "Turkey",        dialCode: "+90",  flag: "🇹🇷", isPopular: true),
        Raw(id: "RU", name: "Russia",        dialCode: "+7",   flag: "🇷🇺", isPopular: true),
        Raw(id: "US", name: "United States", dialCode: "+1",   flag: "🇺🇸", isPopular: true),
        Raw(id: "GB", name: "United Kingdom", dialCode: "+44", flag: "🇬🇧", isPopular: true),

        // Rest, alphabetical.
        Raw(id: "AF", name: "Afghanistan",   dialCode: "+93",  flag: "🇦🇫"),
        Raw(id: "AL", name: "Albania",       dialCode: "+355", flag: "🇦🇱"),
        Raw(id: "DZ", name: "Algeria",       dialCode: "+213", flag: "🇩🇿"),
        Raw(id: "AD", name: "Andorra",       dialCode: "+376", flag: "🇦🇩"),
        Raw(id: "AO", name: "Angola",        dialCode: "+244", flag: "🇦🇴"),
        Raw(id: "AR", name: "Argentina",     dialCode: "+54",  flag: "🇦🇷"),
        Raw(id: "AM", name: "Armenia",       dialCode: "+374", flag: "🇦🇲"),
        Raw(id: "AU", name: "Australia",     dialCode: "+61",  flag: "🇦🇺"),
        Raw(id: "AT", name: "Austria",       dialCode: "+43",  flag: "🇦🇹"),
        Raw(id: "BH", name: "Bahrain",       dialCode: "+973", flag: "🇧🇭"),
        Raw(id: "BD", name: "Bangladesh",    dialCode: "+880", flag: "🇧🇩"),
        Raw(id: "BY", name: "Belarus",       dialCode: "+375", flag: "🇧🇾"),
        Raw(id: "BE", name: "Belgium",       dialCode: "+32",  flag: "🇧🇪"),
        Raw(id: "BZ", name: "Belize",        dialCode: "+501", flag: "🇧🇿"),
        Raw(id: "BJ", name: "Benin",         dialCode: "+229", flag: "🇧🇯"),
        Raw(id: "BT", name: "Bhutan",        dialCode: "+975", flag: "🇧🇹"),
        Raw(id: "BO", name: "Bolivia",       dialCode: "+591", flag: "🇧🇴"),
        Raw(id: "BA", name: "Bosnia",        dialCode: "+387", flag: "🇧🇦"),
        Raw(id: "BW", name: "Botswana",      dialCode: "+267", flag: "🇧🇼"),
        Raw(id: "BR", name: "Brazil",        dialCode: "+55",  flag: "🇧🇷"),
        Raw(id: "BN", name: "Brunei",        dialCode: "+673", flag: "🇧🇳"),
        Raw(id: "BG", name: "Bulgaria",      dialCode: "+359", flag: "🇧🇬"),
        Raw(id: "BF", name: "Burkina Faso",  dialCode: "+226", flag: "🇧🇫"),
        Raw(id: "BI", name: "Burundi",       dialCode: "+257", flag: "🇧🇮"),
        Raw(id: "KH", name: "Cambodia",      dialCode: "+855", flag: "🇰🇭"),
        Raw(id: "CM", name: "Cameroon",      dialCode: "+237", flag: "🇨🇲"),
        Raw(id: "CA", name: "Canada",        dialCode: "+1",   flag: "🇨🇦"),
        Raw(id: "CV", name: "Cape Verde",    dialCode: "+238", flag: "🇨🇻"),
        Raw(id: "CF", name: "Central African Republic", dialCode: "+236", flag: "🇨🇫"),
        Raw(id: "TD", name: "Chad",          dialCode: "+235", flag: "🇹🇩"),
        Raw(id: "CL", name: "Chile",         dialCode: "+56",  flag: "🇨🇱"),
        Raw(id: "CN", name: "China",         dialCode: "+86",  flag: "🇨🇳"),
        Raw(id: "CO", name: "Colombia",      dialCode: "+57",  flag: "🇨🇴"),
        Raw(id: "KM", name: "Comoros",       dialCode: "+269", flag: "🇰🇲"),
        Raw(id: "CG", name: "Congo",         dialCode: "+242", flag: "🇨🇬"),
        Raw(id: "CD", name: "Congo, DR",     dialCode: "+243", flag: "🇨🇩"),
        Raw(id: "CR", name: "Costa Rica",    dialCode: "+506", flag: "🇨🇷"),
        Raw(id: "HR", name: "Croatia",       dialCode: "+385", flag: "🇭🇷"),
        Raw(id: "CU", name: "Cuba",          dialCode: "+53",  flag: "🇨🇺"),
        Raw(id: "CY", name: "Cyprus",        dialCode: "+357", flag: "🇨🇾"),
        Raw(id: "CZ", name: "Czech Republic", dialCode: "+420", flag: "🇨🇿"),
        Raw(id: "DK", name: "Denmark",       dialCode: "+45",  flag: "🇩🇰"),
        Raw(id: "DJ", name: "Djibouti",      dialCode: "+253", flag: "🇩🇯"),
        Raw(id: "EC", name: "Ecuador",       dialCode: "+593", flag: "🇪🇨"),
        Raw(id: "EG", name: "Egypt",         dialCode: "+20",  flag: "🇪🇬"),
        Raw(id: "SV", name: "El Salvador",   dialCode: "+503", flag: "🇸🇻"),
        Raw(id: "GQ", name: "Equatorial Guinea", dialCode: "+240", flag: "🇬🇶"),
        Raw(id: "ER", name: "Eritrea",       dialCode: "+291", flag: "🇪🇷"),
        Raw(id: "EE", name: "Estonia",       dialCode: "+372", flag: "🇪🇪"),
        Raw(id: "ET", name: "Ethiopia",      dialCode: "+251", flag: "🇪🇹"),
        Raw(id: "FJ", name: "Fiji",          dialCode: "+679", flag: "🇫🇯"),
        Raw(id: "FI", name: "Finland",       dialCode: "+358", flag: "🇫🇮"),
        Raw(id: "FR", name: "France",        dialCode: "+33",  flag: "🇫🇷"),
        Raw(id: "GA", name: "Gabon",         dialCode: "+241", flag: "🇬🇦"),
        Raw(id: "GM", name: "Gambia",        dialCode: "+220", flag: "🇬🇲"),
        Raw(id: "GE", name: "Georgia",       dialCode: "+995", flag: "🇬🇪"),
        Raw(id: "DE", name: "Germany",       dialCode: "+49",  flag: "🇩🇪"),
        Raw(id: "GH", name: "Ghana",         dialCode: "+233", flag: "🇬🇭"),
        Raw(id: "GR", name: "Greece",        dialCode: "+30",  flag: "🇬🇷"),
        Raw(id: "GT", name: "Guatemala",     dialCode: "+502", flag: "🇬🇹"),
        Raw(id: "GN", name: "Guinea",        dialCode: "+224", flag: "🇬🇳"),
        Raw(id: "GW", name: "Guinea-Bissau", dialCode: "+245", flag: "🇬🇼"),
        Raw(id: "GY", name: "Guyana",        dialCode: "+592", flag: "🇬🇾"),
        Raw(id: "HT", name: "Haiti",         dialCode: "+509", flag: "🇭🇹"),
        Raw(id: "HN", name: "Honduras",      dialCode: "+504", flag: "🇭🇳"),
        Raw(id: "HK", name: "Hong Kong",     dialCode: "+852", flag: "🇭🇰"),
        Raw(id: "HU", name: "Hungary",       dialCode: "+36",  flag: "🇭🇺"),
        Raw(id: "IS", name: "Iceland",       dialCode: "+354", flag: "🇮🇸"),
        Raw(id: "IN", name: "India",         dialCode: "+91",  flag: "🇮🇳"),
        Raw(id: "ID", name: "Indonesia",     dialCode: "+62",  flag: "🇮🇩"),
        Raw(id: "IR", name: "Iran",          dialCode: "+98",  flag: "🇮🇷"),
        Raw(id: "IQ", name: "Iraq",          dialCode: "+964", flag: "🇮🇶"),
        Raw(id: "IE", name: "Ireland",       dialCode: "+353", flag: "🇮🇪"),
        Raw(id: "IL", name: "Israel",        dialCode: "+972", flag: "🇮🇱"),
        Raw(id: "IT", name: "Italy",         dialCode: "+39",  flag: "🇮🇹"),
        Raw(id: "CI", name: "Ivory Coast",   dialCode: "+225", flag: "🇨🇮"),
        Raw(id: "JP", name: "Japan",         dialCode: "+81",  flag: "🇯🇵"),
        Raw(id: "JO", name: "Jordan",        dialCode: "+962", flag: "🇯🇴"),
        Raw(id: "KZ", name: "Kazakhstan",    dialCode: "+7",   flag: "🇰🇿"),
        Raw(id: "KE", name: "Kenya",         dialCode: "+254", flag: "🇰🇪"),
        Raw(id: "KW", name: "Kuwait",        dialCode: "+965", flag: "🇰🇼"),
        Raw(id: "KG", name: "Kyrgyzstan",    dialCode: "+996", flag: "🇰🇬"),
        Raw(id: "LA", name: "Laos",          dialCode: "+856", flag: "🇱🇦"),
        Raw(id: "LV", name: "Latvia",        dialCode: "+371", flag: "🇱🇻"),
        Raw(id: "LB", name: "Lebanon",       dialCode: "+961", flag: "🇱🇧"),
        Raw(id: "LS", name: "Lesotho",       dialCode: "+266", flag: "🇱🇸"),
        Raw(id: "LR", name: "Liberia",       dialCode: "+231", flag: "🇱🇷"),
        Raw(id: "LY", name: "Libya",         dialCode: "+218", flag: "🇱🇾"),
        Raw(id: "LI", name: "Liechtenstein", dialCode: "+423", flag: "🇱🇮"),
        Raw(id: "LT", name: "Lithuania",     dialCode: "+370", flag: "🇱🇹"),
        Raw(id: "LU", name: "Luxembourg",    dialCode: "+352", flag: "🇱🇺"),
        Raw(id: "MO", name: "Macao",         dialCode: "+853", flag: "🇲🇴"),
        Raw(id: "MK", name: "Macedonia",     dialCode: "+389", flag: "🇲🇰"),
        Raw(id: "MG", name: "Madagascar",    dialCode: "+261", flag: "🇲🇬"),
        Raw(id: "MW", name: "Malawi",        dialCode: "+265", flag: "🇲🇼"),
        Raw(id: "MY", name: "Malaysia",      dialCode: "+60",  flag: "🇲🇾"),
        Raw(id: "MV", name: "Maldives",      dialCode: "+960", flag: "🇲🇻"),
        Raw(id: "ML", name: "Mali",          dialCode: "+223", flag: "🇲🇱"),
        Raw(id: "MT", name: "Malta",         dialCode: "+356", flag: "🇲🇹"),
        Raw(id: "MR", name: "Mauritania",    dialCode: "+222", flag: "🇲🇷"),
        Raw(id: "MU", name: "Mauritius",     dialCode: "+230", flag: "🇲🇺"),
        Raw(id: "MX", name: "Mexico",        dialCode: "+52",  flag: "🇲🇽"),
        Raw(id: "MD", name: "Moldova",       dialCode: "+373", flag: "🇲🇩"),
        Raw(id: "MC", name: "Monaco",        dialCode: "+377", flag: "🇲🇨"),
        Raw(id: "MN", name: "Mongolia",      dialCode: "+976", flag: "🇲🇳"),
        Raw(id: "ME", name: "Montenegro",    dialCode: "+382", flag: "🇲🇪"),
        Raw(id: "MA", name: "Morocco",       dialCode: "+212", flag: "🇲🇦"),
        Raw(id: "MZ", name: "Mozambique",    dialCode: "+258", flag: "🇲🇿"),
        Raw(id: "MM", name: "Myanmar",       dialCode: "+95",  flag: "🇲🇲"),
        Raw(id: "NA", name: "Namibia",       dialCode: "+264", flag: "🇳🇦"),
        Raw(id: "NP", name: "Nepal",         dialCode: "+977", flag: "🇳🇵"),
        Raw(id: "NL", name: "Netherlands",   dialCode: "+31",  flag: "🇳🇱"),
        Raw(id: "NZ", name: "New Zealand",   dialCode: "+64",  flag: "🇳🇿"),
        Raw(id: "NI", name: "Nicaragua",     dialCode: "+505", flag: "🇳🇮"),
        Raw(id: "NE", name: "Niger",         dialCode: "+227", flag: "🇳🇪"),
        Raw(id: "NG", name: "Nigeria",       dialCode: "+234", flag: "🇳🇬"),
        Raw(id: "NO", name: "Norway",        dialCode: "+47",  flag: "🇳🇴"),
        Raw(id: "OM", name: "Oman",          dialCode: "+968", flag: "🇴🇲"),
        Raw(id: "PK", name: "Pakistan",      dialCode: "+92",  flag: "🇵🇰"),
        Raw(id: "PS", name: "Palestine",     dialCode: "+970", flag: "🇵🇸"),
        Raw(id: "PA", name: "Panama",        dialCode: "+507", flag: "🇵🇦"),
        Raw(id: "PG", name: "Papua New Guinea", dialCode: "+675", flag: "🇵🇬"),
        Raw(id: "PY", name: "Paraguay",      dialCode: "+595", flag: "🇵🇾"),
        Raw(id: "PE", name: "Peru",          dialCode: "+51",  flag: "🇵🇪"),
        Raw(id: "PH", name: "Philippines",   dialCode: "+63",  flag: "🇵🇭"),
        Raw(id: "PL", name: "Poland",        dialCode: "+48",  flag: "🇵🇱"),
        Raw(id: "PT", name: "Portugal",      dialCode: "+351", flag: "🇵🇹"),
        Raw(id: "QA", name: "Qatar",         dialCode: "+974", flag: "🇶🇦"),
        Raw(id: "RO", name: "Romania",       dialCode: "+40",  flag: "🇷🇴"),
        Raw(id: "RW", name: "Rwanda",        dialCode: "+250", flag: "🇷🇼"),
        Raw(id: "SA", name: "Saudi Arabia",  dialCode: "+966", flag: "🇸🇦"),
        Raw(id: "SN", name: "Senegal",       dialCode: "+221", flag: "🇸🇳"),
        Raw(id: "RS", name: "Serbia",        dialCode: "+381", flag: "🇷🇸"),
        Raw(id: "SC", name: "Seychelles",    dialCode: "+248", flag: "🇸🇨"),
        Raw(id: "SL", name: "Sierra Leone",  dialCode: "+232", flag: "🇸🇱"),
        Raw(id: "SG", name: "Singapore",     dialCode: "+65",  flag: "🇸🇬"),
        Raw(id: "SK", name: "Slovakia",      dialCode: "+421", flag: "🇸🇰"),
        Raw(id: "SI", name: "Slovenia",      dialCode: "+386", flag: "🇸🇮"),
        Raw(id: "SO", name: "Somalia",       dialCode: "+252", flag: "🇸🇴"),
        Raw(id: "ZA", name: "South Africa",  dialCode: "+27",  flag: "🇿🇦"),
        Raw(id: "KR", name: "South Korea",   dialCode: "+82",  flag: "🇰🇷"),
        Raw(id: "SS", name: "South Sudan",   dialCode: "+211", flag: "🇸🇸"),
        Raw(id: "ES", name: "Spain",         dialCode: "+34",  flag: "🇪🇸"),
        Raw(id: "LK", name: "Sri Lanka",     dialCode: "+94",  flag: "🇱🇰"),
        Raw(id: "SD", name: "Sudan",         dialCode: "+249", flag: "🇸🇩"),
        Raw(id: "SR", name: "Suriname",      dialCode: "+597", flag: "🇸🇷"),
        Raw(id: "SZ", name: "Swaziland",     dialCode: "+268", flag: "🇸🇿"),
        Raw(id: "SE", name: "Sweden",        dialCode: "+46",  flag: "🇸🇪"),
        Raw(id: "CH", name: "Switzerland",   dialCode: "+41",  flag: "🇨🇭"),
        Raw(id: "SY", name: "Syria",         dialCode: "+963", flag: "🇸🇾"),
        Raw(id: "TW", name: "Taiwan",        dialCode: "+886", flag: "🇹🇼"),
        Raw(id: "TJ", name: "Tajikistan",    dialCode: "+992", flag: "🇹🇯"),
        Raw(id: "TZ", name: "Tanzania",      dialCode: "+255", flag: "🇹🇿"),
        Raw(id: "TH", name: "Thailand",      dialCode: "+66",  flag: "🇹🇭"),
        Raw(id: "TG", name: "Togo",          dialCode: "+228", flag: "🇹🇬"),
        Raw(id: "TO", name: "Tonga",         dialCode: "+676", flag: "🇹🇴"),
        Raw(id: "TN", name: "Tunisia",       dialCode: "+216", flag: "🇹🇳"),
        Raw(id: "TM", name: "Turkmenistan",  dialCode: "+993", flag: "🇹🇲"),
        Raw(id: "UG", name: "Uganda",        dialCode: "+256", flag: "🇺🇬"),
        Raw(id: "UA", name: "Ukraine",       dialCode: "+380", flag: "🇺🇦"),
        Raw(id: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "🇦🇪"),
        Raw(id: "UY", name: "Uruguay",       dialCode: "+598", flag: "🇺🇾"),
        Raw(id: "UZ", name: "Uzbekistan",    dialCode: "+998", flag: "🇺🇿"),
        Raw(id: "VU", name: "Vanuatu",       dialCode: "+678", flag: "🇻🇺"),
        Raw(id: "VE", name: "Venezuela",     dialCode: "+58",  flag: "🇻🇪"),
        Raw(id: "VN", name: "Vietnam",       dialCode: "+84",  flag: "🇻🇳"),
        Raw(id: "YE", name: "Yemen",         dialCode: "+967", flag: "🇾🇪"),
        Raw(id: "ZM", name: "Zambia",        dialCode: "+260", flag: "🇿🇲"),
        Raw(id: "ZW", name: "Zimbabwe",      dialCode: "+263", flag: "🇿🇼"),
    ]

    static func byCode(_ code: String) -> Country? {
        all.first { $0.id == code }
    }
}
